# Generated by Django 4.2.13 on 2024-06-14 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
