# Generated by Django 4.2.13 on 2024-06-17 08:29

from django.db import migrations, models
import django.db.models.deletion
import farm.models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_remove_milkingsession_barn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowMass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(blank=True, null=True)),
                ('date_measured', models.DateField(blank=True, null=True)),
            ],
            bases=(models.Model, farm.models.FutureDateValidatorMixin),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
            ],
            bases=(models.Model, farm.models.FutureDateValidatorMixin),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_acquired', models.DateField()),
            ],
            bases=(models.Model, farm.models.FutureDateValidatorMixin),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=100)),
            ],
            bases=(models.Model, farm.models.FutureDateValidatorMixin),
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='farm',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='mating_date',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='pregnancy_status',
        ),
        migrations.RemoveField(
            model_name='calvingrecord',
            name='birthing_complications',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='lactation_status',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='last_milking_date',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='cow',
            name='weight_timestamp',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='users',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='veterinarian',
        ),
        migrations.RemoveField(
            model_name='milkingsession',
            name='milking_duration',
        ),
        migrations.RemoveField(
            model_name='milkingsession',
            name='milking_end_time',
        ),
        migrations.RemoveField(
            model_name='milkingsession',
            name='milking_equipment_used',
        ),
        migrations.RemoveField(
            model_name='milkingsession',
            name='milking_start_time',
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='bull_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='bull_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='inseminator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='last_calving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='no_of_calving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calvingrecord',
            name='birthing_details',
            field=models.TextField(blank=True, help_text='Enter details about the birthing process (optional).', null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vet_company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='vet_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='milkingsession',
            name='milking_date',
            field=models.DateField(default=farm.models.get_default_milking_date),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='mating_bull',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='calvingrecord',
            name='calf_details',
            field=models.TextField(help_text='Enter details about the calf.'),
        ),
        migrations.AlterField(
            model_name='cow',
            name='breed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ApprovalRequest',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.AddField(
            model_name='cowmass',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.cow'),
        ),
    ]
