# Generated by Django 4.2.13 on 2024-06-13 11:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')])),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slogan', models.CharField(blank=True, help_text='Farm motto', max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('INA', 'Inactive'), ('ACT', 'Active')], default='INA', max_length=3)),
                ('verified', models.BooleanField(default=False)),
                ('managers', models.ManyToManyField(related_name='managed_farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created'], name='farms_farm_created_a60df0_idx'), models.Index(fields=['verified'], name='farms_farm_verifie_9b4093_idx'), models.Index(fields=['name'], name='farms_farm_name_b646b2_idx')],
            },
        ),
    ]
