# Generated by Django 4.2.13 on 2024-06-25 02:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_or_tag', models.CharField(max_length=100)),
                ('identifier', models.CharField(editable=False, max_length=100, unique=True)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('slogan', models.CharField(blank=True, help_text='Farm motto', max_length=255, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashamba.farm')),
            ],
        ),
        migrations.CreateModel(
            name='MilkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_yield', models.DecimalField(decimal_places=2, max_digits=6)),
                ('milking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milking_sessions', to='mashamba.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_acquired', models.DateField(default=datetime.date.today)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashamba.farm')),
            ],
            options={
                'verbose_name_plural': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_issue', models.CharField(max_length=255)),
                ('treatment', models.CharField(max_length=255)),
                ('treatment_date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True)),
                ('vet_name', models.CharField(max_length=100)),
                ('vet_company', models.CharField(max_length=100)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashamba.cow')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashamba.farm')),
            ],
        ),
        migrations.CreateModel(
            name='CowMass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.FloatField(blank=True, null=True)),
                ('date_measured', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_measurements', to='mashamba.cow')),
            ],
            options={
                'verbose_name_plural': 'cow masses',
            },
        ),
        migrations.AddField(
            model_name='cow',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashamba.farm'),
        ),
        migrations.CreateModel(
            name='CalvingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calving_date', models.DateField(default=datetime.date.today)),
                ('calf_details', models.TextField(help_text='Enter details about the calf.')),
                ('birthing_details', models.TextField(blank=True, help_text='Enter details about the birthing process (optional).', null=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashamba.cow')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_method', models.CharField(choices=[('AI', 'Artificial Insemination'), ('Natural', 'Natural Mating')], max_length=100)),
                ('bull_name', models.CharField(blank=True, max_length=100)),
                ('bull_code', models.CharField(blank=True, max_length=100)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('repeat_breeding_date', models.DateField(blank=True, null=True)),
                ('last_calving_date', models.DateField(blank=True, null=True)),
                ('no_of_calving', models.IntegerField(blank=True, null=True)),
                ('inseminator_name', models.CharField(blank=True, max_length=100)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mashamba.cow')),
            ],
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['-created'], name='mashamba_fa_created_dee336_idx'),
        ),
    ]
