# Generated by Django 4.2.13 on 2024-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cow',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
