# Generated by Django 4.2.13 on 2024-06-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkingsession',
            name='milking_date',
        ),
        migrations.AddField(
            model_name='milkingsession',
            name='milking_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
