# Generated by Django 4.2.13 on 2024-06-18 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0002_remove_milkingsession_milking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkingsession',
            name='milking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
