# Generated by Django 4.2.13 on 2024-06-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0003_farm_products_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='products_services',
        ),
    ]
