# Generated by Django 4.2.13 on 2024-06-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0005_productservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productservice',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
