# Generated by Django 4.2.13 on 2024-06-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0006_alter_productservice_name_alter_productservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
