# Generated by Django 4.2.13 on 2024-06-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0008_alter_farm_email_alter_farm_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='farm',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='slogan',
            field=models.CharField(blank=True, help_text='Farm motto', max_length=255),
        ),
    ]
