# Generated by Django 4.2.13 on 2024-07-04 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0009_alter_farm_email_alter_farm_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='updated',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='CowMass',
        ),
    ]
