# Generated by Django 4.2.13 on 2024-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0010_cow_mass_cow_updated_delete_cowmass'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
