# Generated by Django 4.2.13 on 2024-07-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mashamba', '0012_milksale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milksale',
            name='farm',
        ),
    ]
